/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/user/get_hh_access_token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hh Access Token */
        get: operations["applications_users_api_get_hh_access_token"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Info
         * @description Получение всей информации пользователя по текущей авторизации
         */
        get: operations["applications_users_api_get_user_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Appuser */
        post: operations["applications_users_api_login_appuser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout Appuser */
        post: operations["applications_users_api_logout_appuser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Appuser */
        post: operations["applications_users_api_register_appuser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/change_password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password Appuser */
        post: operations["applications_users_api_change_password_appuser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Candidates
         * @description Список всех кандидатов в JSON
         */
        get: operations["applications_candidates_api_get_all_candidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Candidate
         * @description Добавить нового кандидата в БД
         */
        post: operations["applications_candidates_api_add_candidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Main Page Search
         * @description Поиск кандидатов внутри БД
         */
        post: operations["applications_candidates_api_main_page_search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/candidates_taken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Candidates Taken
         * @description Список всех отобранных кандидатов в JSON
         */
        get: operations["applications_candidates_api_get_all_candidates_taken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Candidates
         * @description Экспорт кандидатов в csv
         */
        get: operations["applications_candidates_api_export_candidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/export/candidates_taken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Candidates Taken
         * @description Экспорт всех отобранных кандидатов в csv
         */
        get: operations["applications_candidates_api_export_candidates_taken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/specialities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Specialities List
         * @description Список доступных Должностей в БД
         */
        get: operations["applications_candidates_api_get_specialities_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Regions List
         * @description Список доступных Регионов в БД
         */
        get: operations["applications_candidates_api_get_regions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/joborder/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Orders
         * @description Список заявок на подбор персонала
         */
        get: operations["applications_joborders_api_get_job_orders"];
        put?: never;
        /**
         * Add Job Orders
         * @description Добавить новую заявку на подбор
         */
        post: operations["applications_joborders_api_add_job_orders"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/joborder/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Order By Id
         * @description Найти заявку на подбор персонала по id
         */
        get: operations["applications_joborders_api_get_job_order_by_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/joborder/search_crits/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Search Crits
         * @description Список критериев поиска
         */
        get: operations["applications_joborders_api_get_search_crits"];
        put?: never;
        /**
         * Add Search Crits
         * @description Добавить новый критерией парсинга
         */
        post: operations["applications_joborders_api_add_search_crits"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/joborder/search_crits/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Search Crit By Id
         * @description Критерий поиска по id
         */
        get: operations["applications_joborders_api_get_search_crit_by_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/joborder/job_profiles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Profiles
         * @description Список Профилей Должности
         */
        get: operations["applications_joborders_api_get_job_profiles"];
        put?: never;
        /**
         * Add Job Profiles
         * @description Добавить новый Профиль Должности
         */
        post: operations["applications_joborders_api_add_job_profiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/joborder/job_profiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Profile By Id
         * @description Профиль Должности по id
         */
        get: operations["applications_joborders_api_get_job_profile_by_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/joborder/vacancies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Vacancies
         * @description Список Документов Вакансий
         */
        get: operations["applications_joborders_api_get_vacancies"];
        put?: never;
        /**
         * Add Vacancies
         * @description Добавить новый документ Вакансии
         */
        post: operations["applications_joborders_api_add_vacancies"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/joborder/vacancies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Vacancy By Id
         * @description Документ Вакансии по id
         */
        get: operations["applications_joborders_api_get_vacancy_by_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/org/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Org Lst
         * @description Список доступных пользователю организаций
         */
        get: operations["api_org_api_get_org_lst"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/org/all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Org Lst
         * @description Список всех  организаций
         */
        get: operations["api_org_api_get_all_org_lst"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/org/departments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Org Departments Lst
         * @description Список доступных пользователю подразделений организации
         */
        get: operations["api_org_api_get_org_departments_lst"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/org/units/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Org Units Lst
         * @description Список доступных пользователю отделов организации
         */
        get: operations["api_org_api_get_org_units_lst"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/org/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Org Projects Lst
         * @description Список доступных пользователю проектов организации
         */
        get: operations["api_org_api_get_org_projects_lst"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/org/b_areas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Org Business Area Lst
         * @description Список доступных пользователю направлений деятельности организации
         */
        get: operations["api_org_api_get_org_business_area_lst"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hhru/cand/info/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cand Info By Id
         * @description Информация о кандидате с hh.ru по его resume_id
         */
        get: operations["applications_aggregators_api_get_cand_info_by_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hhru/cand/comments/check/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Cand Comments
         * @description Количество комментарив с hh.ru по его resume_id
         */
        get: operations["applications_aggregators_api_check_cand_comments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hhru/cand/comments/update/chl/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Add New Comments To Cands
         * @description ЧИСТАЯ ЛИНИЯ: Обновить комментарий с hh.ru по его resume_id
         */
        put: operations["applications_aggregators_api_add_new_comments_to_cands"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hhru/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hh User Info
         * @description Информация по текущему аккаунту клиента
         */
        get: operations["applications_aggregators_api_get_hh_user_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hhru/me/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hh User Permissions
         * @description Проверка доступа текущего пользователя к платным методам
         */
        get: operations["applications_aggregators_api_get_hh_user_permissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hhru/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Candidates
         * @description Поиск кандидатов посредством парсинга
         */
        post: operations["applications_aggregators_api_search_candidates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hhru/vacancies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Employer Vacancies
         * @description Просмотр опубликованных вакансий выбранным работодателем
         */
        get: operations["applications_aggregators_api_get_employer_vacancies"];
        put?: never;
        /** Publish Vacancy */
        post: operations["applications_aggregators_api_publish_vacancy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hhru/vacancies/{vacancy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Vacancy Info
         * @description Просмотр данных выбранной вакансии
         */
        get: operations["applications_aggregators_api_get_vacancy_info"];
        /**
         * Edit Vacancy
         * @description Редактирование выбранной вакансии
         */
        put: operations["applications_aggregators_api_edit_vacancy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hhru/vacancies/negotiations/{vacancy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Negotiations
         * @description Просмотр откликов по выбранной вакансии
         */
        get: operations["applications_aggregators_api_get_negotiations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hhru/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Connect Hh Account
         * @description Статус подключения аккаунта hh.ru к текущему пользователю
         */
        get: operations["applications_aggregators_api_check_connect_hh_account"];
        put?: never;
        /**
         * Connect Hh Account
         * @description Подключение аккаунт hh.ru к текущему пользователю
         */
        post: operations["applications_aggregators_api_connect_hh_account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hhru/reconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reconnect Hh Account
         * @description Выполнить переподключения аккаунта hh.ru
         */
        get: operations["applications_aggregators_api_reconnect_hh_account"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictor/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export All Candidates Train
         * @description Экспорт всех кандидатов обучения в csv
         */
        get: operations["applications_predictor_api_export_all_candidates_train"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictor/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Available Models List
         * @description Список доступных моделей НС
         */
        get: operations["applications_predictor_api_get_available_models_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictor/models/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Current Model
         * @description Информация по текущей модели НС
         */
        get: operations["applications_predictor_api_check_current_model"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictor/models/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Model Conf
         * @description Сменить действующую модель НС
         */
        post: operations["applications_predictor_api_change_model_conf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictor/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Push Candidates To Train
         * @description Добавление кандидатов в тренировочную таблицу
         */
        get: operations["applications_predictor_api_push_candidates_to_train"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictor/df": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Df From Cand Train
         * @description Создать DataFrame на основе CandidateTrain
         */
        get: operations["applications_predictor_api_get_df_from_cand_train"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictor/xy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Xy Train
         * @description Кортеж (X, y) для обучения модели
         */
        get: operations["applications_predictor_api_get_xy_train"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictor/train": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Train Preditor
         * @description Тренировка модели predictor и сохранение
         */
        get: operations["applications_predictor_api_train_preditor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictor/classify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Classify Cand
         * @description Классификация кандидата из базы данных
         */
        get: operations["applications_predictor_api_classify_cand"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bitrix/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send To Bitrix
         * @description Отправка списка кандидатов в Bitrix
         */
        post: operations["api_bitrix_api_send_to_bitrix"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Debug Form
         * @description Эндпоинт, который принимает любую форму и параметр error
         *     - error: если True, вернуть 401 Unauthorized; если False, вернуть 200 OK
         *     - data: любая форма
         */
        post: operations["api_debug_api_debug_form"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppUserRegisterSchema */
        AppUserRegisterSchema: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
        };
        /** AppUserChangePasswordSchema */
        AppUserChangePasswordSchema: {
            /** New Password */
            new_password: string;
            /** Confirm Password */
            confirm_password: string;
        };
        /**
         * MainPageSearchSchema
         * @description Схема для парсинга внутри БД
         */
        MainPageSearchSchema: {
            /** Speciality */
            speciality: string | null;
            /** Area */
            area: string[] | null;
            /** Relocation Type */
            relocation_type?: string | null;
            /** Schedule */
            schedule?: string[] | null;
            /** Skills */
            skills?: string[] | null;
            /** Experience */
            experience?: number | null;
            /** Gender */
            gender?: string | null;
            /** Age */
            age?: number | null;
            /** Salary */
            salary?: number | null;
            /** Job Search Status */
            job_search_status?: string[] | null;
            /** Limit */
            limit?: number | null;
            /**
             * Page
             * @description Номер страницы
             * @default 0
             */
            page: number | null;
        };
        /** JobOrderSchema */
        JobOrderSchema: {
            /**
             * Id
             * @description Идентификатор Заявки на подбор
             * @default 1
             */
            id: number;
            /**
             * Name
             * @description Навзание заявки в системе
             * @default Заявка 1
             */
            name: string;
            /**
             * Status
             * @description Статус заявки
             * @default Новая
             */
            status: string;
            job_profile: components["schemas"]["JobProfileSchema"];
            criteria: components["schemas"]["SearchCritSchema"];
            /**
             * Priority
             * @description Приоритет заявки
             * @default 1
             */
            priority: number;
            /**
             * Search Limit Target
             * @description Лимит поиска (до)
             * @default 1
             */
            search_limit_target: number;
            /**
             * Is Mass Selection
             * @description Массовый подбор ?
             * @default false
             */
            is_mass_selection: boolean;
            /**
             * Deadline
             * Format: date-time
             * @description Желаемая дата закрытия
             * @default 2024-10-10T17:04:05.124512
             */
            deadline: string;
            /**
             * Is Confirmed
             * @description Утверждена ?
             * @default false
             */
            is_confirmed: boolean;
            /**
             * Description
             * @description Описание/комментарий
             * @default Не указано
             */
            description: string;
            /**
             * Responsible
             * @description Ответственный
             * @default root
             */
            responsible: string;
            /**
             * Created By
             * @description Заявитель
             * @default root
             */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             * @description Дата создания
             * @default 2024-10-10T17:04:05.124606
             */
            created_at: string;
        };
        /** JobProfileSchema */
        JobProfileSchema: {
            /**
             * Id
             * @description Идентификатор Профиля должности
             * @default 1
             */
            id: number;
            /**
             * Name
             * @description Наименование Профиля должности
             * @default Профиль 1
             */
            name: string;
            /**
             * Speciality
             * @description Должность
             * @default Мерчандайзер
             */
            speciality: string;
            /**
             * Org
             * @description Компания
             * @default Чистая Линия
             */
            org: string;
            /**
             * Org Unit
             * @description Подразделение
             * @default Не указано
             */
            org_unit: string;
            /**
             * Org Department
             * @description Отдел
             * @default Не указано
             */
            org_department: string;
            /**
             * Org Job Name
             * @description Должность внутри компании
             * @default Не указано
             */
            org_job_name: string;
            /**
             * Org Project
             * @description Проект компании
             * @default Не указан
             */
            org_project: string;
            /**
             * Org Area Of Business
             * @description Направление деятельности
             * @default Не указан
             */
            org_area_of_business: string;
            /**
             * Job Description
             * @description Обязанности
             * @default
             */
            job_description: string;
            /**
             * Job Conditions
             * @description Условия
             * @default
             */
            job_conditions: string;
            /**
             * Job Requirements
             * @description Требования
             * @default
             */
            job_requirements: string;
            /**
             * Description
             * @description Описание/комментарий
             * @default Не указано
             */
            description: string;
            /**
             * Created At
             * Format: date-time
             * @description Дата создания
             * @default 2024-10-10T17:04:05.120723
             */
            created_at: string;
            /**
             * Created By
             * @description Заявитель
             * @default root
             */
            created_by: string;
        };
        /** SearchCritSchema */
        SearchCritSchema: {
            /**
             * Id
             * @description Идентификатор Критерия поиска
             * @default 1
             */
            id: number;
            /**
             * Name
             * @description Наименование Критерия поиска
             * @default Критирий 1
             */
            name: string;
            /**
             * Speciality
             * @description Должность
             * @default Мерчандайзер
             */
            speciality: string;
            /**
             * Area
             * @description Регион
             * @default Санкт-Петербург
             */
            area: string;
            /**
             * Metro
             * @description Станция метро
             * @default Не указана
             */
            metro: string;
            /**
             * Schedule
             * @description График работы
             * @default fullDay
             */
            schedule: string;
            /**
             * Relocation Type
             * @description Готовность к переезду
             * @default living_or_relocation
             */
            relocation_type: string;
            /**
             * Experience
             * @description Опыт работы (лет)
             * @default 1
             */
            experience: number;
            /**
             * Gender
             * @description Пол
             * @default male
             */
            gender: string;
            /**
             * Age
             * @description Возраст
             * @default 18
             */
            age: number;
            /**
             * Salary
             * @description Зарплата (до)
             * @default 30000
             */
            salary: number;
            /**
             * Job Search Status
             * @description Статус разюме
             * @default active_search
             */
            job_search_status: string;
            /**
             * Created By
             * @description Заявитель
             * @default root
             */
            created_by: string;
        };
        /** ErrorSchema */
        ErrorSchema: {
            /**
             * Error
             * @description Фатальная ошибка
             * @default Emotional DAMAGE!
             */
            error: string;
        };
        /** MessageSchema */
        MessageSchema: {
            /**
             * Msg
             * @description Сообщение о неполадке
             * @default Что-то пошло не так
             */
            msg: string;
        };
        /** JobOrderAddSchema */
        JobOrderAddSchema: {
            /**
             * Name
             * @description Название заявки
             */
            name?: string | null;
            /** Job Profile */
            job_profile: components["schemas"]["JobProfileAddSchema"] | number;
            /** Criteria */
            criteria: components["schemas"]["SearchCritAddSchema"] | number;
            /**
             * Priority
             * @description Приоритет заявки
             * @default 1
             */
            priority: number;
            /**
             * Search Limit Target
             * @description Лимит поиска (до)
             * @default 1
             */
            search_limit_target: number;
            /**
             * Is Mass Selection
             * @description Массовый подбор ?
             * @default false
             */
            is_mass_selection: boolean;
            /**
             * Deadline
             * Format: date-time
             * @description Желаемая дата закрытия
             * @default 2024-10-10T17:04:05.126980
             */
            deadline: string;
            /**
             * Description
             * @description Описание/комментарий
             * @default Не указано
             */
            description: string;
            /**
             * Responsible
             * @description Ответственный
             * @default root
             */
            responsible: string;
        };
        /** JobProfileAddSchema */
        JobProfileAddSchema: {
            /**
             * Name
             * @description Наименование Профиля должности
             * @default Профиль 423759a714c44f369893076665a8111a
             */
            name: string;
            /**
             * Speciality
             * @description Должность
             * @default Мерчандайзер
             */
            speciality: string;
            /**
             * Org
             * @description Компания
             * @default Чистая Линия
             */
            org: string;
            /**
             * Org Unit
             * @description Подразделение
             * @default Не указано
             */
            org_unit: string;
            /**
             * Org Department
             * @description Отдел
             * @default Не указано
             */
            org_department: string;
            /**
             * Org Job Name
             * @description Должность внутри компании
             * @default Не указано
             */
            org_job_name: string;
            /**
             * Org Project
             * @description Проект компании
             * @default Не указан
             */
            org_project: string;
            /**
             * Org Area Of Business
             * @description Направление деятельности
             * @default Не указан
             */
            org_area_of_business: string;
            /**
             * Job Description
             * @description Обязанности
             * @default
             */
            job_description: string;
            /**
             * Job Conditions
             * @description Условия
             * @default
             */
            job_conditions: string;
            /**
             * Job Requirements
             * @description Требования
             * @default
             */
            job_requirements: string;
            /**
             * Description
             * @description Описание/комментарий
             * @default Не указано
             */
            description: string;
        };
        /** SearchCritAddSchema */
        SearchCritAddSchema: {
            /**
             * Name
             * @description Наименование Критерия поиска
             * @default Критерий 99134b7531d046a3b7c50f78a0ce8531
             */
            name: string;
            /**
             * Speciality
             * @description Должность
             * @default Мерчандайзер
             */
            speciality: string | null;
            /**
             * Area
             * @description Регион
             * @default Санкт-Петербург
             */
            area: string | null;
            /**
             * Metro
             * @description Метро
             * @default Не указана
             */
            metro: string | null;
            /**
             * Schedule
             * @description График работы
             * @default fullDay
             */
            schedule: string | null;
            /**
             * Relocation Type
             * @description Готовность к переезду
             * @default living_or_relocation
             */
            relocation_type: string | null;
            /**
             * Experience
             * @description Опыт работы (лет)
             * @default 1
             */
            experience: number | null;
            /**
             * Gender
             * @description Пол
             * @default male
             */
            gender: string | null;
            /**
             * Age
             * @description Возраст
             * @default 18
             */
            age: number | null;
            /**
             * Salary
             * @description Зарплата (до)
             * @default 30000
             */
            salary: number | null;
            /**
             * Job Search Status
             * @description Статус разюме
             * @default active_search
             */
            job_search_status: string | null;
        };
        /**
         * VacancySchema
         * @description Схема публикации вакансии на hh.ru
         */
        VacancySchema: {
            /**
             * Название вакансии
             * @default Тестовая вакансия (не откликаться)
             */
            name: string;
            /**
             * Должность
             * @default Мерчандайзер
             */
            professional_roles: string;
            /**
             * Тип занятости
             * @default part
             */
            employment: string | null;
            /**
             * Регион поиска
             * @default Санкт-Петербург
             */
            area: string;
            salary: components["schemas"]["SalarySchema"];
            /**
             * Тип вакансии
             * @default open
             */
            type: string;
            /**
             * Описание вакансии
             * @default тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест
             */
            description: string;
            /**
             * Система биллинга
             * @default standard
             */
            billing_type: string;
            /**
             * Соискатель с инвалидностью
             * @default false
             */
            accept_handicapped: boolean | null;
            /**
             * Соискатель старше 14
             * @default false
             */
            accept_kids: boolean | null;
            /**
             * Временное трудоустройство
             * @default false
             */
            accept_temporary: boolean | null;
            /**
             * Разрешение на сообщения
             * @default true
             */
            allow_messages: boolean | null;
        };
        /** VacancyAddSchema */
        VacancyAddSchema: {
            /**
             * Name
             * @description Наименование Вакансии
             * @default Вакансия d2c5dbb95a374a548fffa18f1a5476b3
             */
            name: string;
            /** Job Order */
            job_order: components["schemas"]["JobOrderAddSchema"] | number;
            /**
             * Deadline
             * Format: date-time
             * @description Желаемая дата закрытия
             * @default 2024-10-10T17:04:05.132110
             */
            deadline: string;
            /**
             * Responsible
             * @description Ответственный
             * @default root
             */
            responsible: string;
        };
        /** OrgSchema */
        OrgSchema: {
            /** ID */
            id?: number | null;
            /** Название */
            name?: string | null;
        };
        /** OrgDepartmentSchema */
        OrgDepartmentSchema: {
            /** ID */
            id?: number | null;
            /** Организация */
            org: number;
            /** Название */
            name?: string | null;
            /** Описание */
            description?: string | null;
        };
        /** OrgUnitSchema */
        OrgUnitSchema: {
            /** ID */
            id?: number | null;
            /** Подразделение компании */
            department: number;
            /** Название */
            name?: string | null;
            /** Описание */
            description?: string | null;
        };
        /** OrgProjectSchema */
        OrgProjectSchema: {
            /** ID */
            id?: number | null;
            /** Отдел компании */
            unit: number;
            /** Название */
            name?: string | null;
            /** Описание */
            description?: string | null;
        };
        /** OrgBAreaSchema */
        OrgBAreaSchema: {
            /** ID */
            id?: number | null;
            /** Отдел компании */
            unit: number;
            /** Название */
            name?: string | null;
            /** Описание */
            description?: string | null;
        };
        /**
         * CandidateSearchSchema
         * @description Схема фильтров парсинга для api
         */
        CandidateSearchSchema: {
            /**
             * Speciality
             * @description Должность
             * @default Мерчандайзер
             */
            speciality: string;
            /**
             * Area
             * @description Регион
             * @default [
             *       "Санкт-Петербург"
             *     ]
             */
            area: string[];
            /** Relocation Type */
            relocation_type?: string | null;
            /** Schedule */
            schedule?: string[] | null;
            /**
             * Skills
             * @default []
             */
            skills: string[];
            /**
             * Experience
             * @description Суммарный опыт
             * @default 1
             */
            experience: number | string;
            /**
             * Gender
             * @description Пол
             * @default male
             */
            gender: string;
            /**
             * Age
             * @description Возраст (от)
             * @default 18
             */
            age: number;
            /**
             * Salary
             * @description Зарплата (до)
             * @default 200000
             */
            salary: number;
            /**
             * Job Search Status
             * @description Статус резюме
             * @default [
             *       "active_search",
             *       "looking_for_offers"
             *     ]
             */
            job_search_status: string[];
            /**
             * Limit
             * @description Результат на одной странице
             * @default 200
             */
            limit: number;
            /**
             * Page
             * @description Номер страницы
             * @default 0
             */
            page: number | null;
        };
        /** SalarySchema */
        SalarySchema: {
            /**
             * Код валюты из справочника hh.ru
             * @default RUR
             */
            currency: string | null;
            /**
             * Нижняя граница ЗП
             * @description На hh.ru параметр from в соответствии
             * @default 10000
             */
            bottom: number | null;
            /**
             * С вычетом налога
             * @description Признак что границы зарплаты указаны до вычета налогов
             * @default true
             */
            gross: boolean | null;
            /**
             * Верхняя граница ЗП
             * @default 200000
             */
            to: number | null;
        };
        /** VacancyEditSchema */
        VacancyEditSchema: {
            /**
             * Название вакансии
             * @default Тестовая вакансия (не откликаться)
             */
            name: string;
            /**
             * Должность
             * @default Мерчандайзер
             */
            professional_roles: string;
            /**
             * Тип занятости
             * @default part
             */
            employment: string | null;
            /**
             * Регион поиска
             * @default Санкт-Петербург
             */
            area: string;
            salary: components["schemas"]["SalarySchema"];
            /** Type */
            type: null;
            /**
             * Описание вакансии
             * @default тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест
             */
            description: string;
            /**
             * Система биллинга
             * @default standard
             */
            billing_type: string;
            /**
             * Соискатель с инвалидностью
             * @default false
             */
            accept_handicapped: boolean | null;
            /**
             * Соискатель старше 14
             * @default false
             */
            accept_kids: boolean | null;
            /**
             * Временное трудоустройство
             * @default false
             */
            accept_temporary: boolean | null;
            /**
             * Разрешение на сообщения
             * @default true
             */
            allow_messages: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    applications_users_api_get_hh_access_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_users_api_get_user_info: {
        parameters: {
            query?: never;
            header?: {
                jwt?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_users_api_login_appuser: {
        parameters: {
            query: {
                username: string;
                password: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_users_api_logout_appuser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_users_api_register_appuser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppUserRegisterSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_users_api_change_password_appuser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppUserChangePasswordSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_candidates_api_get_all_candidates: {
        parameters: {
            query?: {
                cand_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_candidates_api_add_candidate: {
        parameters: {
            query: {
                cand_id: string;
                speciality: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_candidates_api_main_page_search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MainPageSearchSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_candidates_api_get_all_candidates_taken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_candidates_api_export_candidates: {
        parameters: {
            query?: {
                role_filter?: string | null;
                search_date_from?: string | null;
                search_date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_candidates_api_export_candidates_taken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_candidates_api_get_specialities_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_candidates_api_get_regions_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_joborders_api_get_job_orders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOrderSchema"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
        };
    };
    applications_joborders_api_add_job_orders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobOrderAddSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_joborders_api_get_job_order_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOrderSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
        };
    };
    applications_joborders_api_get_search_crits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchCritSchema"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
        };
    };
    applications_joborders_api_add_search_crits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchCritAddSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_joborders_api_get_search_crit_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchCritSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
        };
    };
    applications_joborders_api_get_job_profiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobProfileSchema"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
        };
    };
    applications_joborders_api_add_job_profiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobProfileAddSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_joborders_api_get_job_profile_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobProfileSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
        };
    };
    applications_joborders_api_get_vacancies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacancySchema"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
        };
    };
    applications_joborders_api_add_vacancies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VacancyAddSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_joborders_api_get_vacancy_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacancySchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
        };
    };
    api_org_api_get_org_lst: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgSchema"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
        };
    };
    api_org_api_get_all_org_lst: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgSchema"][];
                };
            };
        };
    };
    api_org_api_get_org_departments_lst: {
        parameters: {
            query?: {
                org_name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgDepartmentSchema"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
        };
    };
    api_org_api_get_org_units_lst: {
        parameters: {
            query?: {
                org_name?: string;
                department_name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgUnitSchema"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
        };
    };
    api_org_api_get_org_projects_lst: {
        parameters: {
            query?: {
                org_name?: string;
                department_name?: string;
                unit_name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgProjectSchema"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
        };
    };
    api_org_api_get_org_business_area_lst: {
        parameters: {
            query?: {
                org_name?: string;
                department_name?: string;
                unit_name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgBAreaSchema"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorSchema"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
        };
    };
    applications_aggregators_api_get_cand_info_by_id: {
        parameters: {
            query: {
                cand_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_aggregators_api_check_cand_comments: {
        parameters: {
            query: {
                cand_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_aggregators_api_add_new_comments_to_cands: {
        parameters: {
            query?: {
                new_comment?: string;
                cand_id?: string;
                search_date_from?: string;
                search_date_to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_aggregators_api_get_hh_user_info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_aggregators_api_get_hh_user_permissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_aggregators_api_search_candidates: {
        parameters: {
            query?: {
                saveToDB?: boolean;
                without_contacts?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateSearchSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_aggregators_api_get_employer_vacancies: {
        parameters: {
            query?: {
                employer_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_aggregators_api_publish_vacancy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VacancySchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_aggregators_api_get_vacancy_info: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacancy_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_aggregators_api_edit_vacancy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacancy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VacancyEditSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_aggregators_api_get_negotiations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacancy_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_aggregators_api_check_connect_hh_account: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_aggregators_api_connect_hh_account: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_aggregators_api_reconnect_hh_account: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_predictor_api_export_all_candidates_train: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_predictor_api_get_available_models_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_predictor_api_check_current_model: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_predictor_api_change_model_conf: {
        parameters: {
            query: {
                modelName: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_predictor_api_push_candidates_to_train: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_predictor_api_get_df_from_cand_train: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_predictor_api_get_xy_train: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_predictor_api_train_preditor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_predictor_api_classify_cand: {
        parameters: {
            query: {
                resume_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_bitrix_api_send_to_bitrix: {
        parameters: {
            query?: {
                cand_num?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": string[] | null;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_debug_api_debug_form: {
        parameters: {
            query: {
                error: boolean;
                data?: Record<string, never>;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
