/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/user/get_hh_access_token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hh Access Token */
        get: operations["applications_users_api_get_hh_access_token"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Info
         * @description Получение всей информации пользователя по текущей авторизации
         */
        get: operations["applications_users_api_get_user_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Appuser */
        post: operations["applications_users_api_login_appuser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout Appuser */
        post: operations["applications_users_api_logout_appuser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Appuser */
        post: operations["applications_users_api_register_appuser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Candidates
         * @description Список всех кандидатов в JSON
         */
        get: operations["applications_candidates_api_get_all_candidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Candidate
         * @description Добавить нового кандидата в БД
         */
        post: operations["applications_candidates_api_add_candidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Main Page Search
         * @description Поиск кандидатов внутри БД
         */
        post: operations["applications_candidates_api_main_page_search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/candidates_taken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Candidates Taken
         * @description Список всех отобранных кандидатов в JSON
         */
        get: operations["applications_candidates_api_get_all_candidates_taken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Candidates
         * @description Экспорт всех кандидатов в csv
         */
        get: operations["applications_candidates_api_export_candidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/export/candidates_taken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Candidates Taken
         * @description Экспорт всех отобранных кандидатов в csv
         */
        get: operations["applications_candidates_api_export_candidates_taken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/specialities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Specialities List */
        get: operations["applications_candidates_api_get_specialities_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictor/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export All Candidates Train
         * @description Экспорт всех кандидатов обучения в csv
         */
        get: operations["applications_predictor_api_export_all_candidates_train"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictor/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Available Models List
         * @description Список доступных моделей НС
         */
        get: operations["applications_predictor_api_get_available_models_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictor/models/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Current Model
         * @description Информация по текущей модели НС
         */
        get: operations["applications_predictor_api_check_current_model"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictor/models/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Model Conf
         * @description Сменить действующую модель НС
         */
        post: operations["applications_predictor_api_change_model_conf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictor/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Push Candidates To Train
         * @description Добавление кандидатов в тренировочную таблицу
         */
        get: operations["applications_predictor_api_push_candidates_to_train"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictor/df": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Df From Cand Train
         * @description Создать DataFrame на основе CandidateTrain
         */
        get: operations["applications_predictor_api_get_df_from_cand_train"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictor/xy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Xy Train
         * @description Кортеж (X, y) для обучения модели
         */
        get: operations["applications_predictor_api_get_xy_train"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictor/train": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Train Preditor
         * @description Тренировка модели predictor и сохранение
         */
        get: operations["applications_predictor_api_train_preditor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictor/classify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Classify Cand
         * @description Классификация кандидата из базы данных
         */
        get: operations["applications_predictor_api_classify_cand"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hhru/cand_info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cand Info By Id
         * @description Информация о кандидате с hh.ru по его resume_id
         */
        get: operations["api_hhru_api_get_cand_info_by_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hhru/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hh User Info
         * @description Информация по текущему аккаунту клиента
         */
        get: operations["api_hhru_api_get_hh_user_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hhru/me/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hh User Permissions
         * @description Проверка доступа текущего пользователя к платным методам
         */
        get: operations["api_hhru_api_get_hh_user_permissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hhru/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Candidates
         * @description Поиск кандидатов посредством парсинга
         */
        post: operations["api_hhru_api_search_candidates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hhru/vacancies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Employer Vacancies
         * @description Просмотр опубликованных вакансий выбранным работодателем
         */
        get: operations["api_hhru_api_get_employer_vacancies"];
        put?: never;
        /** Publish Vacancy */
        post: operations["api_hhru_api_publish_vacancy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hhru/vacancies/{vacancy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Vacancy Info
         * @description Просмотр данных выбранной вакансии
         */
        get: operations["api_hhru_api_get_vacancy_info"];
        /**
         * Edit Vacancy
         * @description Редактирование выбранной вакансии
         */
        put: operations["api_hhru_api_edit_vacancy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hhru/vacancies/negotiations/{vacancy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Negotiations
         * @description Просмотр откликов по выбранной вакансии
         */
        get: operations["api_hhru_api_get_negotiations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hhru/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Connect Hh Account
         * @description Подключение аккаунт hh.ru к текущему
         */
        post: operations["api_hhru_api_connect_hh_account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bitrix/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send To Bitrix
         * @description Отправка списка кандидатов в Bitrix
         */
        post: operations["api_bitrix_api_send_to_bitrix"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppUserRegisterSchema */
        AppUserRegisterSchema: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
        };
        /**
         * MainPageSearchSchema
         * @description Схема для парсинга внутри БД
         */
        MainPageSearchSchema: {
            /** Specialty */
            specialty?: string | null;
            /** Area */
            area?: string[] | null;
            /** Relocation Type */
            relocation_type?: string | null;
            /** Schedule */
            schedule?: string[] | null;
            /** Skills */
            skills?: string[] | null;
            /** Experience */
            experience?: number | null;
            /** Gender */
            gender?: string | null;
            /** Age */
            age?: number | null;
            /** Salary */
            salary?: number | null;
            /** Job Search Status */
            job_search_status?: string[] | null;
            /** Limit */
            limit?: number | null;
        };
        /**
         * CandidateSearchSchema
         * @description Схема фильтров парсинга для api
         */
        CandidateSearchSchema: {
            /** Specialty */
            specialty: string;
            /** Area */
            area: string[];
            /** Relocation Type */
            relocation_type?: string | null;
            /** Schedule */
            schedule?: string[] | null;
            /**
             * Skills
             * @default []
             */
            skills: string[];
            /** Experience */
            experience: string | number;
            /** Gender */
            gender: string;
            /** Age */
            age: number;
            /** Salary */
            salary: number;
            /** Job Search Status */
            job_search_status: string[];
            /** Limit */
            limit: number;
        };
        /** SalarySchema */
        SalarySchema: {
            /**
             * Код валюты из справочника hh.ru
             * @default RUR
             */
            currency: string | null;
            /**
             * Нижняя граница ЗП
             * @description На hh.ru параметр from в соответствии
             * @default 10000
             */
            bottom: number | null;
            /**
             * С вычетом налога
             * @description Признак что границы зарплаты указаны до вычета налогов
             * @default true
             */
            gross: boolean | null;
            /**
             * Верхняя граница ЗП
             * @default 200000
             */
            to: number | null;
        };
        /**
         * VacancySchema
         * @description Схема публикации вакансии на hh.ru
         */
        VacancySchema: {
            /**
             * Название вакансии
             * @default Тестовая вакансия (не откликаться)
             */
            name: string;
            /**
             * Должность
             * @default Мерчандайзер
             */
            professional_roles: string;
            /**
             * Тип занятости
             * @default part
             */
            employment: string | null;
            /**
             * Регион поиска
             * @default Санкт-Петербург
             */
            area: string;
            salary: components["schemas"]["SalarySchema"];
            /**
             * Тип вакансии
             * @default open
             */
            type: string;
            /**
             * Описание вакансии
             * @default тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест
             */
            description: string;
            /**
             * Система биллинга
             * @default standard
             */
            billing_type: string;
            /**
             * Соискатель с инвалидностью
             * @default false
             */
            accept_handicapped: boolean | null;
            /**
             * Соискатель старше 14
             * @default false
             */
            accept_kids: boolean | null;
            /**
             * Временное трудоустройство
             * @default false
             */
            accept_temporary: boolean | null;
            /**
             * Разрешение на сообщения
             * @default true
             */
            allow_messages: boolean | null;
        };
        /** VacancyEditSchema */
        VacancyEditSchema: {
            /**
             * Название вакансии
             * @default Тестовая вакансия (не откликаться)
             */
            name: string;
            /**
             * Должность
             * @default Мерчандайзер
             */
            professional_roles: string;
            /**
             * Тип занятости
             * @default part
             */
            employment: string | null;
            /**
             * Регион поиска
             * @default Санкт-Петербург
             */
            area: string;
            salary: components["schemas"]["SalarySchema"];
            /** Type */
            type: null;
            /**
             * Описание вакансии
             * @default тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест
             */
            description: string;
            /**
             * Система биллинга
             * @default standard
             */
            billing_type: string;
            /**
             * Соискатель с инвалидностью
             * @default false
             */
            accept_handicapped: boolean | null;
            /**
             * Соискатель старше 14
             * @default false
             */
            accept_kids: boolean | null;
            /**
             * Временное трудоустройство
             * @default false
             */
            accept_temporary: boolean | null;
            /**
             * Разрешение на сообщения
             * @default true
             */
            allow_messages: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    applications_users_api_get_hh_access_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_users_api_get_user_info: {
        parameters: {
            query?: never;
            header?: {
                jwt?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_users_api_login_appuser: {
        parameters: {
            query: {
                username: string;
                password: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_users_api_logout_appuser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_users_api_register_appuser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppUserRegisterSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_candidates_api_get_all_candidates: {
        parameters: {
            query?: {
                cand_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_candidates_api_add_candidate: {
        parameters: {
            query: {
                cand_id: string;
                speciality: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_candidates_api_main_page_search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MainPageSearchSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_candidates_api_get_all_candidates_taken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_candidates_api_export_candidates: {
        parameters: {
            query?: {
                role_filter?: string | null;
                search_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_candidates_api_export_candidates_taken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_candidates_api_get_specialities_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_predictor_api_export_all_candidates_train: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_predictor_api_get_available_models_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_predictor_api_check_current_model: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_predictor_api_change_model_conf: {
        parameters: {
            query: {
                modelName: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_predictor_api_push_candidates_to_train: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_predictor_api_get_df_from_cand_train: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_predictor_api_get_xy_train: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_predictor_api_train_preditor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_predictor_api_classify_cand: {
        parameters: {
            query: {
                resume_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_hhru_api_get_cand_info_by_id: {
        parameters: {
            query: {
                cand_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_hhru_api_get_hh_user_info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_hhru_api_get_hh_user_permissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_hhru_api_search_candidates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateSearchSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_hhru_api_get_employer_vacancies: {
        parameters: {
            query?: {
                employer_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_hhru_api_publish_vacancy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VacancySchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_hhru_api_get_vacancy_info: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacancy_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_hhru_api_edit_vacancy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacancy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VacancyEditSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_hhru_api_get_negotiations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacancy_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_hhru_api_connect_hh_account: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_bitrix_api_send_to_bitrix: {
        parameters: {
            query?: {
                cand_num?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": string[] | null;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
